spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logixspring
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
logix:
  revenue-reduction:
    value-limits:
      30: 5.0
      60: 10.0
      120: 20.0
  jwt-data:
    issuer: @artifactId@
    secret: thisIsTheBigSecret
    algorithm: HMAC512
    duration: 10m
