spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logixspring
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false